apiVersion: v1
kind: ConfigMap
data:
  DB_USERNAME: "ct_admin"
  DB_NAME: "geoconnections"
  DB_HOST: "postgres"
  DB_PORT: "5432"
metadata:
  name: db-env
---
  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: person-env
  data:
    PERSON_SERVICE_ENDPOINT: "http://person-svc-api:5000/"
---
  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: kafka-env
  data:
    KAFKA_URL: kafka-service:9092
    KAFKA_TOPIC: test